name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install & Check Root
        run: |
          bun install
          bun run check

      - name: Install & Check Sbx Engine
        run: |
          cd sbx
          bun install
          bun run check

      - name: Run Tests
        run: bun test
